spring:
  datasource:
    #    DENTRO DE CONTENEDOR DOCKER
    #    url: jdbc:postgresql://db:5432/springboot_db
    #    FUERA DE CONTENEDOR DOCKER
    url: jdbc:postgresql://localhost:5432/springboot_db
    username: prueba
    password: prueba
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true